### ISSUE TITLE
Add endpoint for retrieving all notes of an user

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot#124]
In support of the new UX being developed, we need to create a new endpoint:
GET /api/v1/note
The endpoint, using information about the user from the token, will retrieve all notes created by the particular user.
The notes will be returned as a list of objects.

**Comment by ExtremeSwat** [comment]
I can pick this one.

**Comment by RaduCStefanescu** [comment]
In progress @ExtremeSwat

**Comment by bvizureanu** [comment]
@ExtremeSwat, @RaduCStefanescu is the status of this item current?

**Comment by bvizureanu** [comment]
the endpoint `GET /api/v2/note/` now has an optional `IdObserver`. It does need the polling station ID though. 
How is the client app designed to display the uploaded notes? in the context of a polling station already selected regardless of being checked into a polling station?

@aniri, your input is welcome :D

**Comment by RaduCStefanescu** [comment]
@bvizureanu @aniri @ExtremeSwat I kinda lost track here, is this issue solved?

**Comment by aniri** [comment]
@RaduCStefanescu this issue is still in progress, @ExtremeSwat is working on it. We need to make sure we are covering all possibilities for this new endpoint:

The `IdObserver` should indeed be optional as @bvizureanu mentioned, as we can take this info from claims.

The `pollingStationId` should also be optional, so we will have the possibility of getting all of the notes written by the current user.

The `questionId` should also be optional, with a small mention that if the call is made with a  `questionId`, the `pollingStationId` should also be present.

Also, as a future improvement, we could add a new issue to enhance this endpoint to be used also by admins (update authorization for the endpoint) so they can view a certain observers note (optionally sorted by polling station, or questionid+polling station)

**Comment by RaduCStefanescu** [comment]
Agree with all the above @aniri

**Comment by aniri** [comment]
closing as it was just merged
